#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $PETLY_DB_USER PASSWORD '$PETLY_DB_USER_PASSWORD';
  CREATE DATABASE $PETLY_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $PETLY_DB_NAME TO $PETLY_DB_USER;
EOSQL
